version: '3.1'
services:
  app:
    build: .
    container_name: app-prod
    user: root
    working_dir: /app
    ports:
      - '3000:3000'
    tty: true
    networks:
      - central-net

  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    volumes:
      - ./.mongodb/mongo1:/data/db
      - ./init_config_mongo.sh:/init_config_mongo.sh
    expose:
      - 27017
    ports:
      - 30001:27017
    networks:
      - central-net
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint:
      ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'central-mongo-set']

  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    volumes:
      - ./.mongodb/mongo2:/data/db
    expose:
      - 27017
    ports:
      - 30002:27017
    networks:
      - central-net
    restart: always
    entrypoint:
      ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'central-mongo-set']

  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo
    volumes:
      - ./.mongodb/mongo3:/data/db
    expose:
      - 27017
    ports:
      - 30003:27017
    networks:
      - central-net
    restart: always
    entrypoint:
      ['/usr/bin/mongod', '--bind_ip_all', '--replSet', 'central-mongo-set']

networks:
  central-net:
    driver: bridge
