version: '3.1'
services:
  app:
    image: node:16
    container_name: app
    user: root
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    tty: true
    networks:
      - central-net

networks:
  central-net:
    driver: bridge
